# --- !Ups

CREATE TABLE "phonebook_entries" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY, "name" VARCHAR NOT NULL, "phone_number" VARCHAR NOT NULL);
CREATE INDEX "idx_name" on "phonebook_entries" ("name");
CREATE INDEX "idx_phone_number" on "phonebook_entries" ("phone_number");

# --- !Downs

DROP TABLE "phonebook_entries";